# Generated by Django 4.1.6 on 2023-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_energy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meter_date', models.DateTimeField()),
            ],
        ),
    ]
