# Generated by Django 4.1.6 on 2023-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='active_energy',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
